export const ESTADOS_NOMES: Record<string, string> = {
  AC: "Acre", AL: "Alagoas", AM: "Amazonas", AP: "Amapá", BA: "Bahia",
  CE: "Ceará", DF: "Distrito Federal", ES: "Espírito Santo", GO: "Goiás",
  MA: "Maranhão", MG: "Minas Gerais", MS: "Mato Grosso do Sul", MT: "Mato Grosso",
  PA: "Pará", PB: "Paraíba", PE: "Pernambuco", PI: "Piauí", PR: "Paraná",
  RJ: "Rio de Janeiro", RN: "Rio Grande do Norte", RO: "Rondônia", RR: "Roraima",
  RS: "Rio Grande do Sul", SC: "Santa Catarina", SE: "Sergipe", SP: "São Paulo",
  TO: "Tocantins",
};

export const ESTADOS_CIDADES: Record<string, string[]> = {
  AC: [
    "Rio Branco","Cruzeiro do Sul","Sena Madureira","Tarauacá","Feijó","Brasiléia",
    "Epitaciolândia","Xapuri","Rodrigues Alves","Porto Acre","Mâncio Lima",
    "Acrelândia","Senador Guiomard","Capixaba","Porto Walter","Santa Rosa do Purus",
  ],
  AL: [
    "Maceió","Arapiraca","Palmeira dos Índios","Rio Largo","Penedo","União dos Palmares",
    "São Miguel dos Campos","Satuba","Murici","Delmiro Gouveia","Coruripe","Campo Alegre",
    "Marechal Deodoro","Maribondo","Paripueira","Flexeiras","Joaquim Gomes","Pilar",
    "Porto Calvo","Santana do Ipanema","Viçosa","Igreja Nova","Pão de Açúcar",
  ],
  AM: [
    "Manaus","Parintins","Itacoatiara","Manacapuru","Coari","Tefé","Maués",
    "Tabatinga","São Gabriel da Cachoeira","Humaitá","Lábrea","Manicoré",
    "Borba","Nova Olinda do Norte","Careiro","Autazes","Iranduba","Rio Preto da Eva",
    "Presidente Figueiredo","Barcelos","Eirunepé","Envira","Carauari","Tonantins",
  ],
  AP: [
    "Macapá","Santana","Laranjal do Jari","Oiapoque","Mazagão","Porto Grande",
    "Calçoene","Tartarugalzinho","Pedra Branca do Amapari","Vitória do Jari",
    "Amapá","Serra do Navio","Pracuúba","Ferreira Gomes","Cutias",
  ],
  BA: [
    "Salvador","Feira de Santana","Vitória da Conquista","Camaçari","Juazeiro",
    "Itabuna","Ilhéus","Lauro de Freitas","Jequié","Alagoinhas","Barreiras",
    "Porto Seguro","Simões Filho","Paulo Afonso","Eunápolis","Teixeira de Freitas",
    "Luís Eduardo Magalhães","Santo Antônio de Jesus","Cruz das Almas","Senhor do Bonfim",
    "Valença","Brumado","Guanambi","Serrinha","Itaberaba","Inhambupe","Jacobina",
    "Irecê","Seabra","Bom Jesus da Lapa","Cansanção","Esplanada","Entre Rios",
    "Itamaraju","Medeiros Neto","Mucuri","Nova Viçosa","Poções","Dias d'Ávila",
    "Mata de São João","Candeias","Santo Amaro","Cachoeira","Maragogipe","Nazaré",
    "Amargosa","Conceição do Coité","Riachão do Jacuípe","Tanquinho","Tucano",
    "Ipirá","Itaparica","Madre de Deus","São Francisco do Conde","Pojuca",
  ],
  CE: [
    "Fortaleza","Caucaia","Juazeiro do Norte","Maracanaú","Sobral","Crato",
    "Itapipoca","Maranguape","Iguatu","Quixadá","Canindé","Tianguá","Russas",
    "Limoeiro do Norte","Aquiraz","Pacajus","Horizonte","Eusébio","Cascavel",
    "Aracati","Beberibe","Icó","Jaguaribe","Tauá","Quixeramobim","Senador Pompeu",
    "Morada Nova","Guaraciaba do Norte","Camocim","Acaraú","Cruz","Barbalha",
    "Santana do Cariri","Missão Velha","Brejo Santo","Milagres","Lavras da Mangabeira",
    "Boa Viagem","Pedra Branca","Mombaça","Cratéus","Ipueiras","Independência",
  ],
  DF: [
    "Brasília","Ceilândia","Taguatinga","Planaltina","Samambaia","Santa Maria",
    "Gama","Sobradinho","Recanto das Emas","Guará","Núcleo Bandeirante",
    "Cruzeiro","Lago Sul","Lago Norte","Riacho Fundo","Sudoeste/Octogonal",
    "São Sebastião","Vicente Pires","Águas Claras","Park Way","Candangolândia",
    "Varjão","Fercal","SCIA","Estrutural",
  ],
  ES: [
    "Vitória","Vila Velha","Serra","Cariacica","Linhares","Cachoeiro de Itapemirim",
    "Colatina","Guarapari","São Mateus","Aracruz","Viana","Nova Venécia",
    "Barra de São Francisco","Mimoso do Sul","Marataízes","Piúma","Anchieta",
    "Iconha","Presidente Kennedy","Rio Novo do Sul","Alegre","Guaçuí","Muniz Freire",
    "Iuna","Iúna","Conceição do Castelo","Castelo","Ibatiba","Brejetuba",
    "Afonso Cláudio","Domingos Martins","Santa Maria de Jetibá","Venda Nova do Imigrante",
    "Marechal Floriano","Santa Teresa","São Roque do Canaã","Ecoporanga",
  ],
  GO: [
    "Goiânia","Aparecida de Goiânia","Anápolis","Rio Verde","Luziânia",
    "Águas Lindas de Goiás","Valparaíso de Goiás","Trindade","Formosa","Novo Gama",
    "Senador Canedo","Catalão","Jataí","Itumbiara","Caldas Novas","Inhumas",
    "Mineiros","Goianésia","Planaltina","Goianira","Nerópolis","Bela Vista de Goiás",
    "Santo Antônio do Descoberto","Alexânia","Silvânia","Pires do Rio","Morrinhos",
    "Ceres","Goiás","Porangatu","Niquelândia","Uruaçu","Jaraguá","Itapaci",
    "Mozarlândia","Sanclerlândia","Pirenópolis","Corumbá de Goiás","Anicuns",
    "Iporá","Americano do Brasil","Cidade Ocidental","Cristalina","Luziânia",
  ],
  MA: [
    "São Luís","Imperatriz","São José de Ribamar","Timon","Caxias","Codó",
    "Paço do Lumiar","Açailândia","Bacabal","Balsas","Santa Inês","Barra do Corda",
    "Pinheiro","Chapadinha","Coroatá","Grajaú","Presidente Dutra","Itapecuru Mirim",
    "Brejo","Pedreiras","Viana","Arari","Matões","Zé Doca","Tutóia","Barreirinhas",
    "Humberto de Campos","Icatu","Rosário","Axixá","Urbano Santos","Coelho Neto",
    "Aldeias Altas","Colinas","Tuntum","Lago da Pedra","Lago do Junco",
  ],
  MG: [
    "Belo Horizonte","Uberlândia","Contagem","Juiz de Fora","Betim","Montes Claros",
    "Ribeirão das Neves","Uberaba","Governador Valadares","Ipatinga","Sete Lagoas",
    "Divinópolis","Ibirité","Poços de Caldas","Patos de Minas","Pouso Alegre",
    "Teófilo Otoni","Barbacena","Sabará","Vespasiano","Santa Luzia","Conselheiro Lafaiete",
    "Coronel Fabriciano","Araguari","Curvelo","Muriaé","Ubá","Passos","Ituiutaba",
    "Nova Lima","Lavras","Viçosa","Alfenas","Caratinga","Itabira","João Monlevade",
    "Três Corações","Varginha","Leopoldina","Cataguases","Manhuaçu","Brumadinho",
    "Caeté","Paracatu","Patrocínio","Pirapora","Três Lagoas","Campo Belo",
    "Formiga","Itaúna","Para de Minas","Congonhas","Ouro Preto","Mariana",
    "São João del Rei","Tiradentes","Diamantina","Araçuaí","Almenara","Nanuque",
    "Salinas","Pedra Azul","Porteirinha","Janaúba","Januária","Manga","Bocaiúva",
    "Monjolos","Coração de Jesus","Várzea da Palma","Buritizeiro","Lassance",
    "Engenheiro Navarro","São Francisco","Pompéu","Abaeté","Bom Despacho",
    "Oliveira","Lagoa da Prata","Santo Antônio do Monte","São Gonçalo do Sapucaí",
    "Itajubá","Piranguinho","Wenceslau Brás","Jacuí","Cambuí","Extrema",
    "Itapeva","Monte Azul","Serro","Conceição do Mato Dentro","Datas",
  ],
  MS: [
    "Campo Grande","Dourados","Três Lagoas","Corumbá","Ponta Porã","Naviraí",
    "Nova Andradina","Aquidauana","Paranaíba","Sidrolândia","Maracaju","Caarapó",
    "Rio Brilhante","Nova Alvorada do Sul","São Gabriel do Oeste","Chapadão do Sul",
    "Costa Rica","Cassilândia","Selvíria","Aparecida do Taboado","Bataguassu",
    "Brasilândia","Anastácio","Miranda","Bonito","Jardim","Bela Vista",
    "Amambai","Eldorado","Iguatemi","Ivinhema","Laguna Carapã","Mundo Novo",
    "Glória de Dourados","Deodápolis","Itaquiraí","Paranhos","Porto Murtinho",
  ],
  MT: [
    "Cuiabá","Várzea Grande","Rondonópolis","Sinop","Tangará da Serra","Cáceres",
    "Sorriso","Lucas do Rio Verde","Primavera do Leste","Barra do Garças","Alta Floresta",
    "Colíder","Guarantã do Norte","Juína","Juara","Confresa","São Félix do Araguaia",
    "Água Boa","Pontes e Lacerda","Matupá","Terra Nova do Norte","Peixoto de Azevedo",
    "Novo Progresso","Campos de Júlio","Campo Novo do Parecis","Sapezal",
    "Diamantino","Nortelândia","Alto Araguaia","Alto Garças","Barra do Bugres",
    "Mirassol d'Oeste","Araputanga","São José dos Quatro Marcos","Nova Mutum",
    "Tapurah","Campo Verde","Jaciara","Juscimeira","São Pedro da Cipa",
  ],
  PA: [
    "Belém","Ananindeua","Santarém","Marabá","Castanhal","Parauapebas","Altamira",
    "Abaetetuba","Cametá","Marituba","Itaituba","Tucuruí","Redenção","Capanema",
    "Bragança","Tailândia","Tomé-Açu","Paragominas","Dom Eliseu","Rondon do Pará",
    "Barcarena","Moju","Igarapé-Miri","Mocajuba","Canaã dos Carajás","Ourilândia do Norte",
    "Tucumã","Água Azul do Norte","São Félix do Xingu","Altamira","Porto de Moz",
    "Gurupá","Breves","Bagre","Curralinho","Melgaço","Portel","Almeirim","Prainha",
    "Pacajá","Anapu","Brasil Novo","Medicilândia","Uruará","Placas","Rurópolis",
    "Aveiro","Jacareacanga","Novo Progresso","Trairão","Nhamundá","Faro","Terra Santa",
    "Oriximiná","Óbidos","Alenquer","Monte Alegre","Curuá","Juruti","Santarém Novo",
  ],
  PB: [
    "João Pessoa","Campina Grande","Santa Rita","Patos","Bayeux","Sousa",
    "Guarabira","Cabedelo","Cajazeiras","Esperança","Sapé","Queimadas",
    "Lagoa Seca","Aroeiras","Itaporanga","Princesa Isabel","Pombal","Piancó",
    "Catolé do Rocha","São Bento","Mamanguape","Rio Tinto","Pedras de Fogo",
    "Conde","Lucena","Pitimbu","Alhandra","Cruz do Espírito Santo","Caaporã",
    "Itabaiana","Ingá","Alagoa Grande","Bananeiras","Areia","Pilões","Pilõezinhos",
    "Solânea","Borborema","Alagoa Nova","Brejo do Cruz","São José de Piranhas",
    "Bonito de Santa Fé","Uiraúna","Triunfo","Conceição","Maturéia","Malta",
  ],
  PE: [
    "Recife","Caruaru","Petrolina","Olinda","Paulista","Vitória de Santo Antão",
    "Serra Talhada","Garanhuns","Jaboatão dos Guararapes","Cabo de Santo Agostinho",
    "Camaçari","Caruaru","Abreu e Lima","Igarassu","Ipojuca","Araripina",
    "Arcoverde","Pesqueira","Belo Jardim","Gravatá","Bezerros","Santa Cruz do Capibaribe",
    "Toritama","Surubim","Limoeiro","Carpina","Goiana","Timbaúba","Nazaré da Mata",
    "Itamaracá","Moreno","Camaragibe","São Lourenço da Mata","Maraial","Catende",
    "Palmares","Ribeirão","Barreiros","São Benedito do Sul","Xexéu","Água Preta",
    "Quipapá","Lagoa do Ouro","Lajedo","Bom Conselho","Correntes","Buíque",
    "Tupanatinga","Ibimirim","Inajá","Custódia","Sertânia","Floresta","Salgueiro",
    "Cabrobó","Ouricuri","Bodocó","Exu","Trindade","Ipubi","Santa Filomena",
  ],
  PI: [
    "Teresina","Parnaíba","Picos","Piripiri","Floriano","Campo Maior","Barras",
    "Uruçuí","Bom Jesus","Oeiras","Pedro II","José de Freitas","Piracuruca",
    "Batalha","Buriti dos Lopes","Luís Correia","Água Branca","Valença do Piauí",
    "Corrente","Cristino Castro","Colônia do Gurguéia","Redenção do Gurguéia",
    "Alto Longá","Altos","Beneditinos","Coivaras","Demerval Lobão","Lagoa Alegre",
    "Miguel Leão","Monsenhor Gil","União","Nazária","Teresina",
  ],
  PR: [
    "Curitiba","Londrina","Maringá","Ponta Grossa","Cascavel","São José dos Pinhais",
    "Foz do Iguaçu","Colombo","Guarapuava","Paranaguá","Araucária","Toledo",
    "Apucarana","Umuarama","Pinhais","Almirante Tamandaré","Campo Largo","Piraquara",
    "Sarandi","Fazenda Rio Grande","Cambé","Paranavaí","Francisco Beltrão",
    "Pato Branco","Cianorte","Medianeira","Corbélia","Campo Mourão","Palmas",
    "Irati","Guaratuba","Matinhos","Pontal do Paraná","Lapa","Balsa Nova",
    "Contenda","São João do Triunfo","Palmeira","Castro","Telêmaco Borba",
    "Ortigueira","Jandaia do Sul","Rolândia","Arapongas","Ibiporã","Cornélio Procópio",
    "Bandeirantes","Jacarezinho","Santo Antônio da Platina","Carlópolis","Siqueira Campos",
    "Wenceslau Braz","Quatiguá","Joaquim Távora","Andirá","Cambará","Ribeirão do Pinhal",
    "Londrina","Pitangueiras","Tamarana","Sertanópolis","Assaí","Uraí","Nova Fátima",
    "Mauá da Serra","Faxinal","Manoel Ribas","Ivaiporã","Pitanga","Laranjeiras do Sul",
    "Quedas do Iguaçu","Dois Vizinhos","Capanema","Santo Antônio do Sudoeste",
  ],
  RJ: [
    "Rio de Janeiro","São Gonçalo","Duque de Caxias","Nova Iguaçu","Belford Roxo",
    "Niterói","São João de Meriti","Campos dos Goytacazes","Petrópolis","Volta Redonda",
    "Magé","Itaboraí","Macaé","Cabo Frio","Nova Friburgo","Resende","Angra dos Reis",
    "Mesquita","Nilópolis","Maricá","Teresópolis","Barra Mansa","Itaguaí","Queimados",
    "Japeri","Seropédica","Paracambi","Vassouras","Valença","Rio das Flores",
    "Três Rios","Paraíba do Sul","Sapucaia","Comendador Levy Gasparian","Areal",
    "Miguel Pereira","Paty do Alferes","Mendes","Engenheiro Paulo de Frontin",
    "Rio Claro","Pinheiral","Barra do Piraí","Piraí","Rio das Ostras","Casimiro de Abreu",
    "Búzios","São Pedro da Aldeia","Arraial do Cabo","Araruama","Saquarema",
    "Maricá","Niterói","Itaipuaçu","Iguaba Grande","São Fidélis","Campos dos Goytacazes",
    "Quissamã","Carapebus","Conceição de Macabu","Cardoso Moreira","Italva",
    "Miracema","Itaperuna","Natividade","Porciúncula","Cambuci","Bom Jesus do Itabapoana",
  ],
  RN: [
    "Natal","Mossoró","Parnamirim","São Gonçalo do Amarante","Caicó","Macaíba",
    "Ceará-Mirim","Açu","Nova Cruz","Santa Cruz","Currais Novos","Pau dos Ferros",
    "Apodi","Areia Branca","Touros","São José de Mipibu","Extremoz","Niísia Floresta",
    "Ielmo Marinho","Bom Jesus","Goianinha","Canguaretama","Tibau do Sul","Baía Formosa",
    "São Miguel do Gostoso","Maxaranguape","Pedra Grande","Rio do Fogo","Pureza",
    "João Câmara","Poço Branco","Bento Fernandes","Ruy Barbosa","Lajes","Angicos",
    "Itajá","Fernando Pedroza","Pedreira","Santana do Matos","Florânia","Acari",
    "Carnaúba dos Dantas","Parelhas","Jardim do Seridó","São João do Sabugi",
    "Ouro Branco","São Fernando","Serra Negra do Norte","Alexandria","Marcelino Vieira",
  ],
  RO: [
    "Porto Velho","Ji-Paraná","Ariquemes","Vilhena","Cacoal","Rolim de Moura",
    "Guajará-Mirim","Jaru","Ouro Preto do Oeste","Buritis","Machadinho d'Oeste",
    "Pimenta Bueno","São Miguel do Guaporé","Espigão d'Oeste","Costa Marques",
    "Cerejeiras","Colorado do Oeste","Corumbiara","Chupinguaia","Parecis",
    "Campo Novo de Rondônia","Cujubim","Nova Mamoré","Nova Brasilândia d'Oeste",
    "Alvorada d'Oeste","São Francisco do Guaporé","Ministro Andreazza",
  ],
  RR: [
    "Boa Vista","Rorainópolis","Caracaraí","Alto Alegre","Bonfim","Cantá",
    "Caroebe","Iracema","Mucajaí","Normandia","Pacaraima","Rorainópolis",
    "São João da Baliza","São Luiz","Uiramutã",
  ],
  RS: [
    "Porto Alegre","Caxias do Sul","Pelotas","Canoas","Santa Maria","Gravataí",
    "Viamão","Novo Hamburgo","São Leopoldo","Rio Grande","Alvorada","Passo Fundo",
    "Sapucaia do Sul","Uruguaiana","Santa Cruz do Sul","Cachoeirinha","Bagé",
    "Bento Gonçalves","Erechim","Guaíba","Cachoeira do Sul","Santana do Livramento",
    "São Borja","Alegrete","Ijuí","Montenegro","Santa Rosa","Vacaria","Lajeado",
    "Farroupilha","Veranópolis","Garibaldi","Bento Gonçalves","Carlos Barbosa",
    "Flores da Cunha","Nova Petrópolis","Gramado","Canela","Taquara","São Francisco de Paula",
    "Tramandaí","Osório","Torres","Capão da Canoa","Imbé","Xangri-lá","Maquiné",
    "Arroio do Sal","Pinhal","Cidreira","Balneário Pinhal","Mostardas","Tavares",
    "São José do Norte","Rio Grande","Santa Vitória do Palmar","Jaguarão","Herval",
    "Bagé","Caçapava do Sul","Lavras do Sul","Dom Pedrito","Quaraí","Itaqui",
    "São Luiz Gonzaga","Cerro Largo","Santo Ângelo","Três Passos","Palmeira das Missões",
    "Frederico Westphalen","Planalto","Tenente Portela","Guarani das Missões",
    "Santa Rosa","Horizontina","Tucunduva","Giruá","São Luís das Missões",
    "Cruz Alta","Não-Me-Toque","Panambi","Ijuí","Santa Bárbara do Sul","Tapejara",
    "Selbach","Espumoso","Soledade","Colorado","Passo Fundo","Marau","Getúlio Vargas",
    "Gaurama","Barão de Cotegipe","Erechim","Aratiba","Erval Grande","Três Arroios",
    "Erebango","Jacutinga","Sarandi","Ronda Alta","Lagoa Vermelha","Vacaria",
    "Bom Jesus","São José dos Ausentes","Lages (SC)","Capão Bonito do Sul","Muitos Capões",
  ],
  SC: [
    "Joinville","Florianópolis","Blumenau","São José","Criciúma","Chapecó",
    "Itajaí","Lages","Jaraguá do Sul","Palhoça","Balneário Camboriú","Brusque",
    "Tubarão","Caçador","Camaçari","Indaial","Gaspar","Timbó","Rio do Sul",
    "Videira","Concórdia","São Miguel do Oeste","Araranguá","Mafra","Canoinhas",
    "Porto União","Fraiburgo","Trombudo Central","Ibirama","Taió","Rio do Campo",
    "São Bento do Sul","Corupá","Campo Alegre","Porto Belo","Itapema","Penha",
    "Piçarras","Bombinhas","Navegantes","Biguaçu","Tijucas","Governador Celso Ramos",
    "São João Batista","Antônio Carlos","Rancho Queimado","Angelina","Major Gercino",
    "Botuverá","Guabiruba","Pomerode","Rio dos Cedros","Apiúna","Ascurra",
    "Rodeio","Benedito Novo","Presidente Getúlio","Irupi","Aquiraz",
    "Xanxerê","Xaxim","Pinhalzinho","Maravilha","São Lourenço do Oeste",
    "Guaraciaba","Palma Sola","Descanso","São Miguel do Oeste",
    "Dionísio Cerqueira","São José do Cedro","Romelândia","Belmonte","Guarujá do Sul",
    "Imbituba","Garopaba","Paulo Lopes","Laguna","Imaruí","Capivari de Baixo",
    "Sangão","Gravatal","Braço do Norte","Rio Fortuna","Grão Pará","São Martinho",
    "Jaguaruna","Içara","Sombrio","Santa Rosa do Sul","Torres (RS)",
    "Forquilhinha","Nova Veneza","Urussanga","Cocal do Sul","Morro da Fumaça",
    "Pedras Grandes","Praia Grande","Jacinto Machado","Ermo","Timbé do Sul",
  ],
  SE: [
    "Aracaju","Nossa Senhora do Socorro","Lagarto","Itabaiana","São Cristóvão",
    "Estância","Tobias Barreto","Simão Dias","Nossa Senhora das Dores","Propriá",
    "Boquim","Arauá","Itaporanga d'Ajuda","São Domingos","Moita Bonita",
    "Ribeirópolis","Carira","Frei Paulo","Pedra Mole","Pinhão","Macambira",
    "Pedrinhas","Salgado","Campo do Brito","Riachão do Dantas","Poço Verde",
    "Cristinápolis","Umbaúba","Santa Luzia do Itanhi","Indiaroba","Ilha das Flores",
    "Brejo Grande","Santana do São Francisco","Neópolis","Cedro de São João",
    "Telha","Canhoba","Graccho Cardoso","Gararu","Nossa Senhora de Lourdes",
  ],
  SP: [
    "São Paulo","Guarulhos","Campinas","São Bernardo do Campo","Santo André",
    "Osasco","Ribeirão Preto","Sorocaba","Mauá","São José dos Campos","Mogi das Cruzes",
    "Santos","Diadema","Piracicaba","Bauru","São José do Rio Preto","Jundiaí",
    "Carapicuíba","Franca","Limeira","Taubaté","Praia Grande","Suzano","Barueri",
    "Taboão da Serra","Guarujá","Indaiatuba","Americana","Araraquara","São Vicente",
    "Itaquaquecetuba","Presidente Prudente","São Carlos","Cotia","Itu","Jacareí",
    "Embu das Artes","Caçapava","Hortolândia","Sumaré","São Paulo","Ferraz de Vasconcelos",
    "Itapecerica da Serra","Araçatuba","Paulínia","Cubatão","Marília","Pindamonhangaba",
    "Rio Claro","Botucatu","Pirassununga","Sertãozinho","São João da Boa Vista",
    "Matão","Bebedouro","Jaú","Lençóis Paulista","Birigui","Votuporanga","Fernandópolis",
    "Catanduva","São José do Rio Preto","Barretos","Olímpia","Colina","Bebedouro",
    "Jaboticabal","Monte Alto","Brodowski","Batatais","Nuporanga","São Joaquim da Barra",
    "Orlândia","Guaxupé","Mococa","Espírito Santo do Pinhal","Casa Branca","Itapira",
    "Amparo","Morungaba","Jaguariúna","Pedreira","Monte Mor","Nova Odessa","Santa Bárbara d'Oeste",
    "Americana","Itatiba","Valinhos","Vinhedo","Louveira","Itupeva","Campo Limpo Paulista",
    "Várzea Paulista","Jarinu","Bragança Paulista","Atibaia","Nazaré Paulista","Mairiporã",
    "Caieiras","Pirapora do Bom Jesus","Franco da Rocha","Francisco Morato","Cajamar",
    "Santana de Parnaíba","Pirapora do Bom Jesus","Cajamar","São Roque","Mairinque",
    "Ibiúna","Votorantim","Porto Feliz","Tietê","Capivari","Mombuca","Laranjal Paulista",
    "Boituva","Cerquilho","Tatuí","Itapetininga","Itapeva","Itararé","Capão Bonito",
    "Registro","Miracatu","Juquiá","Sete Barras","Eldorado","Iporanga","Apiaí",
    "Ribeira","Barra do Chapéu","Itapirapuã Paulista","Adrianópolis",
    "Guaratinguetá","Aparecida","Lorena","Cruzeiro","Lagoinha","Monteiro Lobato",
    "São Luís do Paraitinga","Cunha","Ubatuba","Caraguatatuba","Ilhabela","São Sebastião",
    "Bertioga","Mongaguá","Itanhaém","Peruíbe","Miracatu","Iguape","Cananéia",
    "Ilha Comprida","Cajati","Jacupiranga","Barra do Turvo","Pariquera-Açu",
    "Paranapiacaba","Santo André","Mauá","Ribeirão Pires","Rio Grande da Serra",
    "Diadema","São Bernardo do Campo","São Caetano do Sul","Leme","Pirassununga",
    "Porto Ferreira","Descalvado","Analândia","São Pedro","Charqueada","Brotas",
    "Itirapina","São Carlos","Araraquara","Ibaté","Américo Brasiliense","Gavião Peixoto",
    "Rincão","Motuca","Trabiju","Ribeirão Bonito","Bocaina","Dois Córregos","Mineiros do Tietê",
    "Bariri","Itaju","Pederneiras","Bauru","Reginópolis","Cafelândia","Presidente Alves",
    "Pirajuí","Borborema","Guarantã","Guaiçara","Lins","Getulina","Guaimbê","Pongaí",
    "Rinópolis","Pompéia","Marília","Garça","Tupã","Herculândia","Iacri","Quintana",
    "Lucélia","Osvaldo Cruz","Dracena","Junqueirópolis","Monte Castelo","Tupi Paulista",
    "Nova Guataporanga","Panorama","Paulicéia","São João do Pau d'Alho","Ouro Verde",
    "Presidente Bernardes","Mirante do Paranapanema","Rosana","Caiuá","Sandovalina",
    "Teodoro Sampaio","Euclides da Cunha Paulista","Marabá Paulista","Piquerobi",
    "Presidente Prudente","Pirapozinho","Álvares Machado","Presidente Venceslau",
    "Indiana","Regente Feijó","Taciba","Paraguaçu Paulista","Campos Novos Paulista",
    "Rancharia","Assis","Palmital","Borá","Pedrinhas Paulista","Platina","Ibirarema",
    "Manduri","Timburi","Óleo","Salto Grande","Canitar","Ourinhos","Ipaussu","Chavantes",
    "Ribeirão do Sul","Santa Cruz do Rio Pardo","Cerqueira César","Avaré","Itaí",
    "Paranapanema","Arandu","Piraju","São Miguel Arcanjo","Guareí","Sarutaiá","Tejupá",
  ],
  TO: [
    "Palmas","Araguaína","Gurupi","Porto Nacional","Paraíso do Tocantins",
    "Colinas do Tocantins","Guaraí","Miracema do Tocantins","Tocantinópolis",
    "Dianópolis","Pedro Afonso","Alvorada","Formoso do Araguaia","Lagoa da Confusão",
    "Pium","Cristalândia","Figueirópolis","Talismã","Crixás do Tocantins","Conceição do Tocantins",
    "Natividade","Almas","Aurora do Tocantins","Arraias","Novo Alegre","Monte do Carmo",
    "Porto Alegre do Tocantins","São Félix do Tocantins","Mateiros","Ponte Alta do Bom Jesus",
    "Santa Rosa do Tocantins","Taguatinga","Novo Jardim","Combinado","Campos Belos",
    "Araguaçu","Sandolândia","Formosa do Araguaia","Aragominas","Babaçulândia",
    "Filadélfia","Wanderlândia","Araguatins","São Sebastião do Tocantins","Praia Norte",
    "São Miguel do Tocantins","Augustinópolis","Sampaio","Esperantina","Buriti do Tocantins",
  ],
};
